### ISSUE TITLE
IDs of citys are changing over time

### ISSUE THREAD

**Issue by christianheyn** [hunterxxx/covid-frontend#3]
It seems that the IDs of the citys are changing over time. So that the favourit feature doesn't work right. If you pick a city as favourit, the id of that city is stored in local storage.
Now the ID of that city changes and the wrong city is showen as favorite.

**Comment by hunterxxx** [comment]
I have falsely replaced the id after the favourite code snippet and deployed it. The ID was meant to show the total number of cities. The ID code has been removed since the last commit as the mobile screen could not fit too many column information. Perhaps if you try to favourite again / refresh the local storage, will it work fine?

**Comment by christianheyn** [comment]
THX
